In [215]:
import numpy as np
import pandas as pd

In [5]:
# Create an array of 10 zeros
arr_zeros = np.zeros(10)
arr_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
#Create an array of 10 ones
arr_ones = np.ones(10)
arr_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
#Create an array f 10 fives
arr_fives = np.full(10,5)
arr_fives

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [15]:
#Create an array of integers from 10 to 50
arr = np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [23]:
#Create an array of all even integers from 10 to 50
arr_even = arr[arr %2 == 0] 
arr_even

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [33]:
#6. Create a 3x3 matrix with values ranging from 0 to 8.
arr2 = np.arange(0,9)
arr2.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
#7. Create a 3x3 identity matrix.
eye = np.eye(3,3)
eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
#8. Use NumPy to generate a random number between 0 and 1.
arr3 = np.random.rand()
arr3

0.8349305091560695

In [49]:
#9. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution.
arr_normal = np.random.randn(25)
arr_normal

array([-0.83070526, -0.15209518,  0.89688136, -0.71309359,  0.82821705,
       -0.17930744,  0.57965126,  0.35019797, -0.03861357,  2.46541348,
       -2.1184541 , -0.61299344, -1.37421103, -0.26294024, -0.32130251,
       -0.12475906, -0.3783573 ,  0.09569381, -0.93881101,  1.44081225,
       -0.85882831,  0.63934932, -0.3597391 , -0.41423679, -0.74633002])

In [51]:
#10. Create an array of 20 linearly spaced points between 0 and 1.
linspace = np.linspace(0,1,20)
linspace

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [57]:
#11. Create a 5x5 matrix with values from 1 to 25.
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [69]:
#12. Extract the first row of a 2D array.
arr[0]

array([1, 2, 3, 4, 5])

In [67]:
#13. Extract the last column of a 2D array.
arr[-1]

array([21, 22, 23, 24, 25])

In [73]:
#14. Find the sum of all elements in an array.
total = arr.sum()
total

325

In [75]:
#15. Find the standard deviation of an array.
std = arr.std()
std

7.211102550927978

In [141]:
#16. Find the index of the maximum value in an array.
arr_max_index = arr.argmax()
arr_max_index

24

In [145]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [163]:
#17. Sort an array in ascending order.
arr_sort = np.sort(arr)
arr_sort

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [189]:
#18. Reverse an array.
arr_demo = np.arange(0,10)
print(arr_demo[: : -1])
arr_reverse = np.flip(arr)
arr_reverse

[9 8 7 6 5 4 3 2 1 0]


array([[25, 24, 23, 22, 21],
       [20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [191]:
arr_diag = np.diag(arr)
arr_diag

array([ 1,  7, 13, 19, 25])

In [199]:
arr =np.array([4,5,6,7])
arr_eye = np.eye(4)*arr
arr_eye

array([[4., 0., 0., 0.],
       [0., 5., 0., 0.],
       [0., 0., 6., 0.],
       [0., 0., 0., 7.]])

In [212]:
#20. Create a 4x4 matrix with random integers between 1 and 100.
arr_random = np.random.randint(1,100,(4,4))
arr_random

array([[12, 25, 65, 76],
       [50,  7, 80,  8],
       [56, 84, 11, 39],
       [45, 59, 89,  1]])

# Pandas

In [223]:
## 1. Create a DataFrame with columns 'A', 'B', and 'C' and rows labeled 'Row1', 'Row2', and 'Row3'.
mycolumns = ['A','B','C']
rows = ['row1','row2','row3']
mydata = np.random.randint(1,10,(3,3))
df = pd.DataFrame(data=mydata,index=rows, columns=mycolumns)
df

A  B  C
row1  4  1  2
row2  3  3  9
row3  8  8  1

In [227]:
## 2. Select only the 'A' column from the DataFrame.
df['A']

row1    4
row2    3
row3    8
Name: A, dtype: int32

In [229]:
# 3. Select both the 'A' and 'C' columns from the DataFrame.
df['A','C']

KeyError: ('A', 'C')