# pandas 

In [3]:
import numpy as np
import pandas as pd

numpy array has numeric index
pandas series has a labelled index(data is internally still numerically organized)
panda series we can have only one data column
therefore pandas dataframe comes where we can have any number of data columns(multiple series with same index is dataframe)

In [6]:
#Creating a pandas series
myindex = ['USA','canada','England']
mydata = [1776,1867,1821]

In [8]:
#Series with default integer index
myser = pd.Series(data = mydata)
print("Series with default index: \n",myser)

Series with default index: 
 0    1776
1    1867
2    1821
dtype: int64


In [10]:
#creating a series with a custom index
myser = pd.Series(data=mydata,index=myindex)
print("series with named index: \n",myser)

series with named index: 
 USA        1776
canada     1867
England    1821
dtype: int64


In [12]:
#Creating Series with numpy array
ran_data = np.random.randint(0,100,4)
print("\nRandom data from numpy array:",ran_data)


Random data from numpy array: [34 89 72 49]


In [14]:
names = ['Alice','Bob','Charles','Dave']
ages = pd.Series(ran_data,index=names)
print("\nseries from NumPy array: \n" , ages)


series from NumPy array: 
 Alice      34
Bob        89
Charles    72
Dave       49
dtype: int32


In [18]:
#Creating a series from a dictionary

ages_dict = {'Sammy':5,'Frank':10,'Spike': 7}
print("\nSeries from dictionary is\n", pd.Series(ages_dict))


Series from dictionary is
 Sammy     5
Frank    10
Spike     7
dtype: int64


In [28]:
#Creating Series from imaginary Sales Data
Q1 = {'Japan':80,'China':450,'India':200,'USA':260}
Q2 = {'Brazil':100,'China':500,'India':210,'USA':250}
sales_Q1= pd.Series(Q1)
sales_Q2 = pd.Series(Q2)

print(sales_Q1)
print(sales_Q2)

Japan     80
China    450
India    200
USA      260
dtype: int64
Brazil    100
China     500
India     210
USA       250
dtype: int64


In [34]:
#Accessing values by Named Index
print("Sales in Japan from Q1", sales_Q1['Japan'])


Sales in Japan from Q1 80


In [36]:
#Accessing values from Integer based Location
print("Sales in Japan from Q1", sales_Q1[0])

Sales in Japan from Q1 80


C:\Users\dbda.STUDENTSDC\AppData\Local\Temp\ipykernel_8128\2511499439.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print("Sales in Japan from Q1", sales_Q1[0])


In [40]:
#Errors 
print(sales_Q1['France]) # Non-Existant keys
print(sales_Q1['USA ']) 
print(sales_Q1[ 'usa'])

SyntaxError: unterminated string literal (detected at line 2) (3405288444.py, line 2)

In [51]:
#7 Series Operations
print("Series Keys: ", sales_Q1.keys())

Series Keys:  Index(['Japan', 'China', 'India', 'USA'], dtype='object')


In [57]:
#8 Broadcasting operations 
print("Sales Q1 doubled", sales_Q1 * 2)
print("Sales Q1 doubled", sales_Q1 / 100)

Sales Q1 doubled Japan    160
China    900
India    400
USA      520
dtype: int64
Sales Q1 doubled Japan    0.8
China    4.5
India    2.0
USA      2.6
dtype: float64


In [59]:
#Handling Mismatched Indices (NaN values)
print("\nSalesQ1 + Sales Q2(with Nan where Non matching keys)\n", sales_Q1 + sales_Q2 )


SalesQ1 + Sales Q2(with Nan where Non matching keys)
 Brazil      NaN
China     950.0
India     410.0
Japan       NaN
USA       510.0
dtype: float64


In [65]:
#Handling missin data (Filling NaN with default value)
print("\n Sales Q1 + Sales Q2(fill naN with 0):\n", sales_Q1.add(sales_Q2, fill_value=0))


 Sales Q1 + Sales Q2(fill naN with 0):
 Brazil    100.0
China     950.0
India     410.0
Japan      80.0
USA       510.0
dtype: float64


# DataFrame

In [19]:
#creating a simple datafram from existing python list
np.random.seed(101) ##set seed for reproducibility

mydata = np.random.randint(0,101,(4,3))
print("Generated Data (mydata):\n",mydata)


Generated Data (mydata):
 [[95 11 81]
 [70 63 87]
 [75  9 77]
 [40  4 63]]


In [21]:
myindex = ['CA','NY','AZ','TX']
mycolumns = ['jan','feb','Mar']



In [23]:
#Create data frame without index and columns
df = pd.DataFrame(data=mydata)
print("\nDatFrame without index/columns:\n",df)


DatFrame without index/columns:
     0   1   2
0  95  11  81
1  70  63  87
2  75   9  77
3  40   4  63


In [25]:
#Create DataFrame with bith custom index and column names
df = pd.DataFrame(data=mydata,index=myindex)
print("\nDataFrame with custom row index:\n",df)


DataFrame with custom row index:
      0   1   2
CA  95  11  81
NY  70  63  87
AZ  75   9  77
TX  40   4  63


In [27]:
##Creating data frame with custom inbdex and custom columns
df = pd.DataFrame(data=mydata,index=myindex,columns=mycolumns)
print("\n data Frame with custom inbdex and custom columns:\n",df)


 data Frame with custom inbdex and custom columns:
     jan  feb  Mar
CA   95   11   81
NY   70   63   87
AZ   75    9   77
TX   40    4   63


In [29]:
##Displaying information about Dta Frame
print("\n DataFrame info")
print(df.info())


 DataFrame info
<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, CA to TX
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   jan     4 non-null      int32
 1   feb     4 non-null      int32
 2   Mar     4 non-null      int32
dtypes: int32(3)
memory usage: 80.0+ bytes
None


In [31]:
#Create dataframe from csv files
print("***************************************************************")
df= pd.read_csv('tips.csv')
print(df)
print(df.columns)
print("***************************************************************")
print(df.index)
print("***************************************************************")
print(df.head(3))
print("***************************************************************")
print(df.tail(3))
print("***************************************************************")
print(df.info())
print("***************************************************************")
print(len(df))
print("***************************************************************")
print(df.describe())
print("***************************************************************")
print(df.describe().transpose())
print("***************************************************************")

***************************************************************
   Total Bill   Tip     Sex Smoker  Day    Time  Size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female    Yes  Sun  Dinner     4
Index(['Total Bill', 'Tip', 'Sex', 'Smoker', 'Day', 'Time', 'Size'], dtype='object')
***************************************************************
RangeIndex(start=0, stop=5, step=1)
***************************************************************
   Total Bill   Tip     Sex Smoker  Day    Time  Size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
***************************************************************
   Total Bill   Tip     Sex Smoker  Day    Time  Size
2       21.01  3.50    Male  

In [33]:
#Selecting a single column
print(df['total_bill'])
print(type())

KeyError: 'total_bill'

In [ ]:
#Selecting multiple columns
print(df[['Total Bill','Tip']])

In [169]:
#Create a new column based on existing one

df['tip_per'] = 100*df['Tip']/df['Total Bill']
df['price_per_person']= df['Total Bill']/df['Size']
print(df.head())

   Total Bill   Tip     Sex Smoker  Day    Time  Size Time_mapped    tip_per  \
0       16.99  1.01  Female     No  Sun  Dinner     2           D   5.944673   
1       10.34  1.66    Male     No  Sun  Dinner     3           D  16.054159   
2       21.01  3.50    Male     No  Sun  Dinner     3           D  16.658734   
3       23.68  3.31    Male     No  Sun  Dinner     2           D  13.978041   
4       24.59  3.61  Female    Yes  Sun  Dinner     4           D  14.680765   

   price_per_person  
0          8.495000  
1          3.446667  
2          7.003333  
3         11.840000  
4          6.147500  


In [171]:
##Adjust the price % column by rounding to 2 decimal
df['price_per_person'] = np.round(df['price_per_person'],2)
print(df.head())

   Total Bill   Tip     Sex Smoker  Day    Time  Size Time_mapped    tip_per  \
0       16.99  1.01  Female     No  Sun  Dinner     2           D   5.944673   
1       10.34  1.66    Male     No  Sun  Dinner     3           D  16.054159   
2       21.01  3.50    Male     No  Sun  Dinner     3           D  16.658734   
3       23.68  3.31    Male     No  Sun  Dinner     2           D  13.978041   
4       24.59  3.61  Female    Yes  Sun  Dinner     4           D  14.680765   

   price_per_person  
0              8.49  
1              3.45  
2              7.00  
3             11.84  
4              6.15  


In [ ]:
###remove the 'tip % column '
df = df.drop('tip_per',axis =1)
print(df.head())

In [ ]:
###Show all columns in the display

###now after seting if we prnt df it will show whole dataframe 

pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)
print(df)

print(df.head(2))

In [173]:
###
pd.reset_option('display.max_columns',None)
pd.reset_option('display.max_rows',None)
print(df.head())

   Total Bill   Tip     Sex Smoker  Day    Time  Size Time_mapped    tip_per  \
0       16.99  1.01  Female     No  Sun  Dinner     2           D   5.944673   
1       10.34  1.66    Male     No  Sun  Dinner     3           D  16.054159   
2       21.01  3.50    Male     No  Sun  Dinner     3           D  16.658734   
3       23.68  3.31    Male     No  Sun  Dinner     2           D  13.978041   
4       24.59  3.61  Female    Yes  Sun  Dinner     4           D  14.680765   

   price_per_person  
0              8.49  
1              3.45  
2              7.00  
3             11.84  
4              6.15  


In [175]:
##Accessing rows by index
print(df.iloc[0].transpose())

Total Bill             16.99
Tip                     1.01
Sex                   Female
Smoker                    No
Day                      Sun
Time                  Dinner
Size                       2
Time_mapped                D
tip_per             5.944673
price_per_person        8.49
Name: 0, dtype: object


In [42]:
#Pandas COnditional Filtering
#Conditions on single column

print(df['Total Bill']< 30) # Boolean Series
#print(df.Toal Bill < 30 ) This is wrong because we have space in out column name so use 
#print(df.Total_Bill) this will work
print(df[df['Total Bill']< 30]) 


0    True
1    True
2    True
3    True
4    True
Name: Total Bill, dtype: bool
   Total Bill   Tip     Sex Smoker  Day    Time  Size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female    Yes  Sun  Dinner     4


In [45]:
#Filter rows based on gender 
print(df[df['Sex']=='Female'])

   Total Bill   Tip     Sex Smoker  Day    Time  Size
0       16.99  1.01  Female     No  Sun  Dinner     2
4       24.59  3.61  Female    Yes  Sun  Dinner     4


In [64]:
#Multiple conditions (AND,OR,NOT)
print(df[(df['Total Bill'] > 20)& (df['Sex']=='Male')] )
print("********")
print(df[(df['Total Bill'] > 20)& ~(df['Sex']=='Male')] )
print("********")
print(df[(df['Total Bill'] > 20) | (df['Sex']=='Male')] )


   Total Bill   Tip   Sex Smoker  Day    Time  Size
2       21.01  3.50  Male     No  Sun  Dinner     3
3       23.68  3.31  Male     No  Sun  Dinner     2
********
   Total Bill   Tip     Sex Smoker  Day    Time  Size
4       24.59  3.61  Female    Yes  Sun  Dinner     4
********
   Total Bill   Tip     Sex Smoker  Day    Time  Size
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female    Yes  Sun  Dinner     4


In [68]:
#Using 'in' for checking if a column value is on a list of options 
options = ['Sat', 'Sun']
print(df[df['Day'].isin(options)])
print(df[(df['Day'] =='Sun') | (df['Day'] =='Sat')])

   Total Bill   Tip     Sex Smoker  Day    Time  Size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female    Yes  Sun  Dinner     4
   Total Bill   Tip     Sex Smoker  Day    Time  Size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female    Yes  Sun  Dinner     4


In [72]:
#Pandas Useful methods
#Sort values by tip
print(df.sort_values('Tip').head())
print(df.sort_values('Tip', ascending=False).head())

   Total Bill   Tip     Sex Smoker  Day    Time  Size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
2       21.01  3.50    Male     No  Sun  Dinner     3
4       24.59  3.61  Female    Yes  Sun  Dinner     4
   Total Bill   Tip     Sex Smoker  Day    Time  Size
4       24.59  3.61  Female    Yes  Sun  Dinner     4
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
0       16.99  1.01  Female     No  Sun  Dinner     2


In [74]:
#Calculate correlation between total bill and tip
print(df[['Total Bill' , 'Tip']].corr())

            Total Bill       Tip
Total Bill    1.000000  0.791002
Tip           0.791002  1.000000


In [78]:
###finding index of min and max of total bill
print("Max of Total Bill:",df['Total Bill'].max())
print("Min of total Bill:",df['Total Bill'].min())

print("Index of max total bill:",df['Total Bill'].idxmax())
print("Index of min total bill:",df['Total Bill'].idxmin())

Max of Total Bill: 24.59
Min of total Bill: 10.34
Index of max total bill: 4
Index of min total bill: 1


In [92]:
##get unique values in the categorical column
print(df['Smoker'].value_counts())

Smoker
No     4
Yes    1
Name: count, dtype: int64


In [84]:
print(df['Sex'].value_counts())

Sex
Male      3
Female    2
Name: count, dtype: int64


In [94]:
###get unique values and count of unique values
print(df['Size'].unique())
print(df['Size'].nunique())

[2 3 4]
3


In [177]:
##Map 'Dinner' to D and 'Lunch' to 'L'
df['Time_mapped'] = df['Time'].map({'Dinner' : 'D' , 'Lunch':'L'})
print(df[['Time','Time_mapped']].head())
df

     Time Time_mapped
0  Dinner           D
1  Dinner           D
2  Dinner           D
3  Dinner           D
4  Dinner           D


Total Bill   Tip     Sex Smoker  Day    Time  Size Time_mapped    tip_per  \
0       16.99  1.01  Female     No  Sun  Dinner     2           D   5.944673   
1       10.34  1.66    Male     No  Sun  Dinner     3           D  16.054159   
2       21.01  3.50    Male     No  Sun  Dinner     3           D  16.658734   
3       23.68  3.31    Male     No  Sun  Dinner     2           D  13.978041   
4       24.59  3.61  Female    Yes  Sun  Dinner     4           D  14.680765   

   price_per_person  
0              8.49  
1              3.45  
2              7.00  
3             11.84  
4              6.15

In [104]:
###check the duplicates and drop them

print("duplicate rows are:",df.duplicated().sum())  ##count of duplicate rows
df_no_duplicates=df.drop_duplicates()
print(df_no_duplicates.head())

duplicate rows are: 0
   Total Bill   Tip     Sex Smoker  Day    Time  Size Time_mapped
0       16.99  1.01  Female     No  Sun  Dinner     2           D
1       10.34  1.66    Male     No  Sun  Dinner     3           D
2       21.01  3.50    Male     No  Sun  Dinner     3           D
3       23.68  3.31    Male     No  Sun  Dinner     2           D
4       24.59  3.61  Female    Yes  Sun  Dinner     4           D


In [106]:
###Use between() to filter values between a range
filtered_df = df[df['Total Bill'].between(10,20,inclusive='both')]
print(filtered_df)

   Total Bill   Tip     Sex Smoker  Day    Time  Size Time_mapped
0       16.99  1.01  Female     No  Sun  Dinner     2           D
1       10.34  1.66    Male     No  Sun  Dinner     3           D


In [112]:
### Sample Random Data
print(df.sample(2))
print(df.sample(frac=0.2))  ##Randomly sample 10% of rows

   Total Bill   Tip     Sex Smoker  Day    Time  Size Time_mapped
4       24.59  3.61  Female    Yes  Sun  Dinner     4           D
0       16.99  1.01  Female     No  Sun  Dinner     2           D
   Total Bill   Tip   Sex Smoker  Day    Time  Size Time_mapped
3       23.68  3.31  Male     No  Sun  Dinner     2           D


In [116]:
####Get n largest and smallest values by Tip
print(df.nlargest(2,'Tip'))
print(df.nsmallest(2,'Tip'))

   Total Bill   Tip     Sex Smoker  Day    Time  Size Time_mapped
4       24.59  3.61  Female    Yes  Sun  Dinner     4           D
2       21.01  3.50    Male     No  Sun  Dinner     3           D
   Total Bill   Tip     Sex Smoker  Day    Time  Size Time_mapped
0       16.99  1.01  Female     No  Sun  Dinner     2           D
1       10.34  1.66    Male     No  Sun  Dinner     3           D


In [122]:
###Grouping
'''
# Groupby functionality
1. **Splitting** : the data is divided into groups based on criteria provided
2. **Applying** : A Function (or multiple function) is applied to each group independently
3. **Combining** : The Results of the functions applications are combined into a new DtatFrame

'''

'\n# Groupby functionality\n1. **Splitting** : the data is divided into groups based on criteria provided\n2. **Applying** : A Function (or multiple function) is applied to each group independently\n3. **Combining** : The Results of the functions applications are combined into a new DtatFrame\n\n'

In [139]:
#1 Spliiting group by Gender
df_grouped = df.groupby('Sex')
print(df_grouped)
print(df_grouped.head())

   Total Bill   Tip     Sex Smoker  Day    Time  Size Time_mapped
0       16.99  1.01  Female     No  Sun  Dinner     2           D
1       10.34  1.66    Male     No  Sun  Dinner     3           D
2       21.01  3.50    Male     No  Sun  Dinner     3           D
3       23.68  3.31    Male     No  Sun  Dinner     2           D
4       24.59  3.61  Female    Yes  Sun  Dinner     4           D


In [159]:
# 2 . Applying - Calculate various statistics for 'tip' by 'gender'
sum_Tip_Sex = df_grouped['Tip'].sum() #Mean tip by Gender
print(sum_Tip_Sex)

mean_Tip_Sex = df_grouped['Tip'].mean() 
print(mean_Tip_Sex)

count_Tip_Sex = df_grouped['Tip'].count()
print(count_Tip_Sex)



Sex
Female    4.62
Male      8.47
Name: Tip, dtype: float64
Sex
Female    2.310000
Male      2.823333
Name: Tip, dtype: float64
Sex
Female    2
Male      3
Name: Tip, dtype: int64


In [161]:
# 3 . Combining - Group by both 'Gender' and 'Day'
df_grouped_day = df.groupby(['Sex', 'Day'])
mean_Tip_by_Gender_Day = df_grouped_day['Tip'].mean()    #Mean tip by gender and day
print(mean_Tip_by_Gender_Day)

Sex     Day
Female  Sun    2.310000
Male    Sun    2.823333
Name: Tip, dtype: float64


In [163]:
# 4 Aggregation with multiple functions
df_grouped_agg = df.groupby(['Sex', 'Day']).agg({'Tip': ['mean', 'sum','count']})
print(df_grouped_agg)

                 Tip            
                mean   sum count
Sex    Day                      
Female Sun  2.310000  4.62     2
Male   Sun  2.823333  8.47     3


In [167]:
#Resetting INdex 
df_grouped_agg = df.groupby(['Sex', 'Day']).agg({'Tip': ['mean', 'sum','count']}).reset_index()
print(df_grouped_agg)

      Sex  Day       Tip            
                    mean   sum count
0  Female  Sun  2.310000  4.62     2
1    Male  Sun  2.823333  8.47     3
