In [19]:
import numpy as np

In [13]:
arr1 = np.array([1,2,3,4]) ## 1D array from list
arr1

array([1, 2, 3, 4])

In [15]:
arr2 = np.array([[1,2,3],[4,5,6]]) ## 2D array from list
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
arr3 = np.array((7,8,9)) ## 1D array from tuple
arr3

array([7, 8, 9])

In [73]:
zeros = np.zeros((2,3)) ## 2x3 array of zeros
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [75]:
ones = np.ones((3,2)) ##3x2 array of ones
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [77]:
identity = np.eye(3) ##3x3 identity matrix
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [89]:
empty1= np.empty((3,4)) ##unintialized array
empty1

array([[1.02986250e-311, 2.81617418e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.11260619e-306, 6.82116729e-043, 5.45292150e-090,
        1.02290481e+166],
       [5.44890177e-067, 6.28102225e+174, 6.48224659e+170,
        4.93432906e+257]])

In [81]:
full = np.full((3,3),7) ### 2x2 array filled with 7
full

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [47]:
#creating array with range

range_arr = np.arange(0,10,2) ###gives 1D array with 2 gap between each element
range_arr

array([0, 2, 4, 6, 8])

In [99]:
linspace_arr = np.linspace(0,1,6) ##gives 5 elements between 0 to 1
linspace_arr

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [53]:
rand = np.random.rand(2,3) ### 2x3 matrix of values between 0 to 1
rand

array([[0.27048772, 0.67831245, 0.13732954],
       [0.53624702, 0.98030046, 0.10157955]])

In [57]:
rand_int = np.random.randint(1,10,(2,2)) ##gives integer values between 1 to 10
rand_int

array([[4, 8],
       [5, 4]])

In [59]:
rand_custom_normal = np.random.normal(5,2,(2,3)) ### normal distribution with mean=5 and std = 2
rand_custom_normal

array([[-0.29902948,  6.33861309,  5.87091633],
       [ 4.27795617,  3.57793059,  5.49249786]])

In [101]:
rand__normal = np.random.randn(2,3) #Random numbers from standard normal distribution 
rand_normal

array([[-0.29902948,  6.33861309,  5.87091633],
       [ 4.27795617,  3.57793059,  5.49249786]])

In [21]:
reshaped = np.arange(12).reshape(3,4) ###1D array to 3x4
reshaped

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
init_like = np.zeros_like(reshaped) ##arrays of zeros witth same shape as reshaped
init_like

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [29]:
arr = np.arange(0,11) # Creating sample array
print("Initial Array", arr)

Initial Array [ 0  1  2  3  4  5  6  7  8  9 10]


In [31]:
#Bracket Indexing and Selection
#Get a value at index
print("Value at Index", arr[8])

Value at Index 8


In [41]:
#Get values in range 
print("Values in range 1 to 5", arr[1:5])
print("Values in range 0 to 5", arr[0:5])

Values in range 1 to 5 [1 2 3 4]
Values in range 0 to 5 [0 1 2 3 4]


In [47]:
#Broadcasting 
#Setting values with index range
arr[0:5] = 100
print("After broadcasting with 100", arr)

After broadcasting with 100 [100 100 100 100 100   5   6   7   8   9  10]


In [49]:
#Reset array

arr = np.arange(0,11)
print("Print arr", arr)

Print arr [ 0  1  2  3  4  5  6  7  8  9 10]


In [51]:
#Important notes on slices
slices_of_arr = arr[0:6]
print("Slice of array [0:6]", arr[0:6])

Slice of array [0:6] [0 1 2 3 4 5]


In [53]:
#CHange slice
slices_of_arr[:] = 99
print("After modifying ", arr)

After modifying  [99 99 99 99 99 99  6  7  8  9 10]


In [57]:
#To get a copy
arr_copy = arr.copy()
print("Copy of array", arr_copy)

arr_copy[:] = 22
print("Original Array and copid array", arr, arr_copy)

Copy of array [99 99 99 99 99 99  6  7  8  9 10]
Original Array and copid array [99 99 99 99 99 99  6  7  8  9 10] [22 22 22 22 22 22 22 22 22 22 22]


In [61]:
#2D arrays
arr_2d = np.array(([5,10,15], [20,25,30], [35,40,45]))
print("2D array", arr_2d)


2D array [[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [63]:
#Indexing row
print("Seconf row of 2D array", arr_2d[1])

Seconf row of 2D array [20 25 30]


In [71]:
#Getting individual element value
print("Element at [1,0]:", arr_2d[1][0])
print("Element at [1,0]: (alternative syntax)", arr_2d[1,0])

Element at [1,0]: 20
Element at [1,0]: (alternative syntax) 20


In [75]:
#2D slicing
print("Shape (2,2) from top right corner:\n", arr_2d[:2, 1:])
print("Shape (2,2) from top right corner:\n(alternative syntax)", arr_2d[2, :])

Shape (2,2) from top right corner:
 [[10 15]
 [25 30]]
Shape (2,2) from top right corner:
(alternative syntax) [35 40 45]


In [79]:
#Conditional Selection
arr = np.arange(1,11)
print("Array for conditional selection",arr)

Array for conditional selection [ 1  2  3  4  5  6  7  8  9 10]


In [95]:
#check  conditional
print("conditional array > 4 ",arr>4)
print("conditional array > 4 ",arr[arr>4])

conditional array > 4  [False False False False  True  True  True  True  True  True]
conditional array > 4  [ 5  6  7  8  9 10]


In [89]:
#store boolean array in another array
bool_arr = arr >4
print("boolean array for array >4",bool_arr)

boolean array for array >4 [False False False False  True  True  True  True  True  True]


In [97]:
#Select elements where condition is true

print("printing values where condition is true",arr[bool_arr])

printing values where condition is true [ 5  6  7  8  9 10]


In [99]:
#using condition directly in selection
print("conditional array > 2 ",arr[arr>2])

conditional array > 2  [ 3  4  5  6  7  8  9 10]


In [105]:
#Using a variable for condition
x = 2
print("elements where  arr > x (x=2):", arr[arr > x])

elements where  arr > x (x=2): [ 3  4  5  6  7  8  9 10]


In [107]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [131]:
#shape of array
arr2 = arr.reshape(3,3)
print("arr2 of 3x3:",arr2)
print(arr2.shape)
print(arr2.size) # gives rows x columns 
print(arr.shape)
print(arr.size)

arr2 of 3x3: [[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
9
(9,)
9


Summary Statistics

In [115]:
#Summary statistics
print("Sum of elements:",arr.sum())
print("mean of elements:", arr.mean())
print("Maximum Value:",arr.max())
print("Minimum value:",arr.min())
print("Variance:",arr.var())
print("Standard Deviation:",arr.std())

Sum of elements: 45
mean of elements: 5.0
Maximum Value: 9
Minimum value: 1
Variance: 6.666666666666667
Standard Deviation: 2.581988897471611
